
services:

  db:
    image: postgres:15-alpine
    container_name: stack_bridge_db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stack_bridge

    ports:
     - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  
  api:
    build: .
    container_name: stack_bridge_api
    restart: always

    depends_on:
      - db

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: stack_bridge
      JWT_SECRET_KEY: hihihahahihihahahihihahahihihaha
      JWT_ALGORITHM: HS256
      JWT_ISSUER: stack_bridge_backend
      JWT_AUDIENCE_USER: stack-bridge-users
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 15
      JWT_REFRESH_SECRET_KEY: ahahahahahahahahahahahahahahahah
      JWT_REFRESH_TOKEN_EXPIRE_DAYS: 30
      JWT_AUDIENCE_REFRESH: stack-bridge-users-refresh

    ports:
      - "8000:8000"
    
volumes:
  postgres_data: